# Copy this file to: lrangell/ankura/.github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  cargo-test:
    name: Cargo Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install pkl CLI
        run: |
          curl -L -o pkl https://github.com/apple/pkl/releases/download/0.29.1/pkl-macos-aarch64
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          
      - name: Run cargo tests
        run: cargo test
        
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        
      - name: Check formatting
        run: cargo fmt --check

  pkl-test:
    name: Pkl Test  
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install pkl CLI
        run: |
          curl -L -o pkl https://github.com/apple/pkl/releases/download/0.29.1/pkl-macos-aarch64
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          
      - name: Run pkl tests
        run: pkl test pkl-tests/

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cargo-audit
        run: cargo install cargo-audit
        
      - name: Run security audit
        run: cargo audit