name: Homebrew Formula CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-formula:
    name: Validate Formula
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formula syntax
        run: |
          # Basic checks for Ruby formula structure
          if ! grep -q "class Ankura < Formula" Formula/ankura.rb; then
            echo "❌ Formula class declaration not found"
            exit 1
          fi
          
          if ! grep -q 'depends_on "pkl"' Formula/ankura.rb; then
            echo "❌ pkl dependency not found"
            exit 1
          fi
          
          echo "✅ Formula structure valid"

      - name: Validate workflow files
        run: |
          # Check that workflow YAML files are valid
          python -c "import yaml; yaml.safe_load(open('.github/workflows/release.yml'))"
          python -c "import yaml; yaml.safe_load(open('.github/workflows/ci.yml'))"
          echo "✅ Workflow files valid"

  test-scripts:
    name: Test Build Scripts
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test script syntax
        run: |
          # Check shell scripts for syntax errors
          bash -n scripts/build-release.sh
          bash -n scripts/update-formula.sh
          echo "✅ Shell scripts valid"