name: Update Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., v0.2.1)'
        required: true
      x86_checksum:
        description: 'x86_64 SHA256 checksum'
        required: true  
      arm_checksum:
        description: 'ARM64 SHA256 checksum'
        required: true

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout homebrew repo
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_no_v=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          # Update version and checksums
          sed -i "s/version \".*\"/version \"${{ steps.get_version.outputs.version_no_v }}\"/" Formula/ankura.rb
          
          # Update Intel checksum (first occurrence)
          sed -i "0,/sha256 \".*\"/{s/sha256 \".*\"/sha256 \"${{ github.event.inputs.x86_checksum }}\"/}" Formula/ankura.rb
          
          # Update ARM checksum (second occurrence) 
          sed -i "0,/sha256 \".*\"/{/sha256 \"${{ github.event.inputs.x86_checksum }}\"/!s/sha256 \".*\"/sha256 \"${{ github.event.inputs.arm_checksum }}\"/}" Formula/ankura.rb

      - name: Verify formula syntax
        run: |
          # Basic syntax check
          grep -q "version \"${{ steps.get_version.outputs.version_no_v }}\"" Formula/ankura.rb
          grep -q "${{ github.event.inputs.x86_checksum }}" Formula/ankura.rb  
          grep -q "${{ github.event.inputs.arm_checksum }}" Formula/ankura.rb

      - name: Commit updated formula
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/ankura.rb
          git commit -m "Update formula for ${{ steps.get_version.outputs.version }}

          - Updated version to ${{ steps.get_version.outputs.version_no_v }}
          - Updated x86_64 checksum: ${{ github.event.inputs.x86_checksum }}
          - Updated arm64 checksum: ${{ github.event.inputs.arm_checksum }}"
          git push